#!/bin/sh
#
# Monit Process Monitor configuration for OPNsense
# Generates all drop-in configs for custom services
#

DROPIN_DIR="/usr/local/etc/monit.opnsense.d"

configure() {
    mkdir -p "$DROPIN_DIR"

    # === Generate OpenVPN monitors ===
    cat > "$DROPIN_DIR/openvpn.conf" << EOF
# OpenVPN Instance Monitoring - Generated by Custom Config
# Auto-restart crashed OpenVPN instances
EOF

    for conf in /var/etc/openvpn/instance-*.conf; do
        [ -f "$conf" ] || continue
        uuid=$(basename "$conf" | sed "s/instance-//;s/.conf//")
        # Use short uuid for process name
        short_uuid=$(echo "$uuid" | cut -c1-8)
        cat >> "$DROPIN_DIR/openvpn.conf" << EOF

check process openvpn_${short_uuid} matching "$uuid"
    start program = "/usr/local/sbin/openvpn --config $conf --daemon"
    stop program = "/usr/bin/pkill -f $uuid"
    if does not exist then restart
EOF
    done
    echo "Generated openvpn.conf"

    # === Generate VPN Bypass Sniffer monitor ===
    cat > "$DROPIN_DIR/vpnbypass_sniffer.conf" << EOF
# VPN Bypass DNS Sniffer Monitor - Generated by Custom Config
check process vpnbypass_sniffer matching "vpnbypass_sniffer"
    start program = "/usr/local/opnsense/scripts/OPNsense/CustomConfig/vpnbypass_sniffer.py start"
    stop program = "/usr/local/opnsense/scripts/OPNsense/CustomConfig/vpnbypass_sniffer.py stop"
    if does not exist then restart
    if 5 restarts within 5 cycles then alert
EOF
    echo "Generated vpnbypass_sniffer.conf"

    # === Generate Gateway Watcher monitor ===
    cat > "$DROPIN_DIR/gateway_monitors.conf" << EOF
# Gateway Watcher Monitor - Generated by Custom Config
check process gateway_watcher matching "gateway_watcher.php"
    start program = "/usr/sbin/service dpinger restart" with timeout 30 seconds
    stop program = "/usr/sbin/service dpinger stop"
    if does not exist then restart
    if 5 restarts within 5 cycles then alert
EOF
    echo "Generated gateway_monitors.conf"

    # Reload monit
    if pgrep -q monit; then
        /usr/local/bin/monit reload 2>/dev/null
        echo "Monit reloaded"
    else
        /usr/local/bin/monit 2>/dev/null
        echo "Monit started"
    fi
}

status() {
    echo "=== Monit Drop-in Configs ==="
    ls -la "$DROPIN_DIR"/*.conf 2>/dev/null
    echo ""
    echo "=== Monit Summary ==="
    /usr/local/bin/monit summary 2>/dev/null || echo "Monit not running"
}

case "$1" in
    configure) configure ;;
    status) status ;;
    *) echo "Usage: $0 {configure|status}"; exit 1 ;;
esac
